---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://www.ph.utexas.edu/~siva/wizkey/ 
base_path : /~siva/wizkey/


posts:
  permalink: /:categories/:title/
  summary_lines: 1
#  latest: 10

pages:
  permalink: 'pretty'
