title : Whizkey Seminar
author :
  name : Whizkey seminar group
#  email : blah@email.test
#  github : username
#  twitter : username
#  feedburner : feedname

#hack to get the site logo pointing correctly
home_url : http://www.ph.utexas.edu/~siva/whizkey/

navigation :
  - about.md
  - archive.html
  - calendar.html
#  - tags.html
  - semesters.html
#  - pages.html
  
