title : Whizkey Seminar
author :
  name : Whizkey seminar group
#  email : blah@email.test
#  github : username
#  twitter : username
#  feedburner : feedname

navigation :
  - about.md
  - archive.html
#  - tags.html
  - categories.html
#  - pages.html
  
